### ISSUE TITLE
Investigate possible future modding support

### ISSUE THREAD

**Issue by Abb4** [cloudchasingmeerkat/laverna#14]
- maybe allow players to import own scripts
  - lua would be good scripting language for this, since its very accessible
- maybe allow to import own levels
  - creating navmeshes could prove difficult for this

**Comment by cloudchasingmeerkat** [comment]
Godot 4 doesn't support the Lua plugin (currenty). Therefore it's not really feasible to discuss this topic until we have a Godot plugin which supports the embedding of Lua code.
